/* house-recon county proxy — Cloudflare Worker.
 *
 * County auditor portals are public government sites without bot protection,
 * but they send no CORS headers, so the browser analyzer can't read them
 * directly. This Worker does the small HTTP dance the portal needs
 * (session cookie -> address search -> datalet pages), strips the HTML to
 * text, and returns JSON with CORS. Responses are cached for a day.
 *
 * The flow is an adapter for the iasWorld Public Access platform (Tyler
 * Technologies), which many county auditors run. Adding another iasWorld
 * county is one COUNTIES entry (probe it first: the /search/commonsearch.aspx
 * form must exist and accept number+street). Other platforms (Devnet wEdge,
 * Vision, WTH GIS, ...) need their own small lookup functions.
 *
 * Routes:
 *   GET /<county-slug>?number=123&street=Main
 *     -> { ok, county, name, state, matches, sections: { profileall,
 *          value_history, tax_info_all, permits } }  (stripped page text)
 *
 * Deploy: npx wrangler login && npx wrangler deploy   (from this directory)
 * Local:  npx wrangler dev --port 8799
 */

"use strict";

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36";

// County registry lives in counties.js (auto-generated by the discovery
// crawler, each entry verified against the live portal). Two platforms:
//   platform "iasworld": { base, prefix } — Tyler iasWorld Public Access
//   platform "wth":      { base, map }   — WTH GIS (Indiana)
import { COUNTIES } from "./counties.js";

// Datalet modes worth having, fetched only where the county's own nav offers
// them (mode names vary per county: Franklin has histvalue, Lake has
// payment_history, Butler has value_history/tax_info_all, ...).
const MODE_WISHLIST = ["profileall", "value_history", "histvalue",
  "tax_info_all", "payment_history", "sales", "permits"];
const MAX_MODE_FETCHES = 5;

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Max-Age": "86400",
};

function json(body, status = 200, extra = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...CORS, ...extra },
  });
}

// HTML -> plain text, tables kept row-per-line with tab-separated cells
// (mirrors the shape the analyzer's parsers expect).
function stripHtml(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<(tr|\/tr|table|\/table|p|\/p|br|div|\/div|li|h\d)[^>]*>/gi, "\n")
    .replace(/<\/(td|th)>/gi, "\t")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/ /g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&#39;/g, "'")
    .replace(/[ \t]*\n[ \t]*/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[ \t]{2,}/g, " ");
}

function hiddenFields(html) {
  const out = {};
  const rx = /<input[^>]+type="hidden"[^>]+name="([^"]+)"[^>]*value="([^"]*)"/g;
  let m;
  while ((m = rx.exec(html))) out[m[1]] = m[2];
  return out;
}

// Workers' fetch drops Set-Cookie headers from intermediate redirect hops,
// and these ASP.NET portals often mint the session cookie ON a redirect
// (commonsearch -> Disclaimer). So: follow redirects manually, collecting
// cookies from every hop into a jar sent with every request.
function jarCollect(res, jar) {
  const cs = typeof res.headers.getSetCookie === "function"
    ? res.headers.getSetCookie()
    : [res.headers.get("set-cookie") || ""];
  for (const c of cs) {
    const kv = (c || "").split(";")[0].trim();
    if (kv && kv.includes("=")) jar.map.set(kv.split("=")[0], kv);
  }
  jar.cookie = [...jar.map.values()].join("; ");
}

async function jarFetch(url, opts, jar, follow = true) {
  let u = url;
  let cur = opts;
  for (let i = 0; i < 6; i++) {
    const res = await fetch(u, {
      ...cur,
      redirect: "manual",
      headers: { ...(cur.headers || {}),
                 ...(jar.cookie ? { Cookie: jar.cookie } : {}) },
    });
    jarCollect(res, jar);
    if (follow && res.status >= 300 && res.status < 400) {
      const loc = res.headers.get("location");
      if (!loc) return res;
      u = new URL(loc, u).toString();
      cur = { headers: cur.headers }; // redirected requests become GETs
      continue;
    }
    return res;
  }
  throw new Error("too many redirects");
}

async function iasWorldLookup(cfg, number, street) {
  const root = cfg.base + cfg.prefix;
  const headers = { "User-Agent": UA };
  const jar = { map: new Map(), cookie: "" };
  let r1 = await jarFetch(`${root}/search/commonsearch.aspx?mode=address`,
                          { headers }, jar);
  let html1 = await r1.text();

  // Some counties gate on a disclaimer postback before showing the form.
  // The agree control is an <input> on some portals and a <button> on
  // others (e.g. /PT installs) — the server only honors the POST when the
  // btAgree field is present, any value.
  if (html1.includes("btAgree") && !html1.includes("inpNumber")) {
    const f = hiddenFields(html1);
    const am = html1.match(
      /<(?:input|button)[^>]+name="(btAgree[^"]*)"(?:[^>]*value="([^"]*)")?/);
    if (am) f[am[1]] = am[2] || "";
    await jarFetch(r1.url, {
      method: "POST",
      headers: { ...headers,
                 "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams(f).toString(),
    }, jar);
    r1 = await jarFetch(`${root}/search/commonsearch.aspx?mode=address`,
                        { headers }, jar);
    html1 = await r1.text();
  }
  if (!html1.includes("inpNumber")) {
    return { ok: false, error: "portal changed",
             detail: "address search form not found on the county portal" };
  }

  const form = hiddenFields(html1);
  Object.assign(form, {
    hdAction: "Search", hdIndex: "0", sIndex: "0",
    inpNumber: number, inpStreet: street,
    selSortBy: "PARID", selSortDir: "asc", selPageSize: "15",
    btSearch: "Search",
  });
  const r2 = await jarFetch(`${root}/search/commonsearch.aspx?mode=address`, {
    method: "POST",
    headers: { ...headers,
               "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams(form).toString(),
  }, jar, false);

  // Unique match: 302 straight to the datalet. Multiple matches: a results
  // page whose rows carry selectSearchRow('../Datalets/Datalet.aspx?...')
  // links — take the first (closest) row and report the count. Some portals
  // 302 to the results page instead; VISITING it is what establishes the
  // server-side row state the datalet needs, so follow and scan it.
  let dataletQs = null;
  let matches = 1;
  const scanRows = body => {
    const hrefs = [...body.matchAll(/Datalet\.aspx\?(sIndex=\d+&(?:amp;)?idx=\d+)/gi)]
      .map(m => m[1].replace(/&amp;/g, "&"));
    if (hrefs.length) {
      dataletQs = hrefs[0];
      matches = new Set(hrefs).size;
    }
  };
  if (r2.status >= 300 && r2.status < 400) {
    const loc = r2.headers.get("location") || "";
    const qm = loc.match(/datalet\.aspx\?(.+)$/i);
    if (qm) {
      dataletQs = qm[1];
    } else if (loc) {
      const rr = await jarFetch(
        new URL(loc, `${root}/search/`).toString(), { headers }, jar);
      scanRows(await rr.text());
    }
  } else {
    scanRows(await r2.text());
  }
  if (!dataletQs) {
    return { ok: false, error: "no match",
             detail: "the address search returned no parcels — try just the " +
               "street number and street name (no suffix)" };
  }

  // Hit the row's datalet URL exactly as the results page links it —
  // capitalized path and a Referer, like a browser. Some counties
  // (Franklin) serve empty chrome without both, and the first hit also
  // sets the session's "current parcel" state the mode pages need.
  const dataletHeaders = {
    ...headers,
    Referer: `${root}/search/commonsearch.aspx?mode=address`,
  };
  const sections = {};
  const raw = await jarFetch(`${root}/Datalets/Datalet.aspx?${dataletQs}`,
                             { headers: dataletHeaders }, jar);
  const rawHtml = await raw.text();
  sections.profile = stripHtml(rawHtml);

  // Fetch only the extra modes this county's own nav actually offers.
  const offered = new Set(
    [...rawHtml.matchAll(/mode=([a-z_]+)/gi)].map(m => m[1].toLowerCase()));
  const wanted = MODE_WISHLIST.filter(m => offered.has(m))
    .slice(0, MAX_MODE_FETCHES);
  for (const mode of wanted) {
    const u = `${root}/Datalets/Datalet.aspx?mode=${mode}&${dataletQs}`;
    const rr = await jarFetch(u, { headers: dataletHeaders }, jar);
    sections[mode] = stripHtml(await rr.text());
  }

  // Success signal: a parcel-id label, or (some portals never print one on
  // the profile view) the parcel attribute fields themselves.
  const allText = Object.values(sections).join("\n");
  const hasRecord = /(?:PARID|Parcel Number|Parcel ID):/i.test(allText) ||
    (/Land Use (?:Code|Description)/i.test(allText) &&
     /(?:District Name|Taxing District)/i.test(allText));
  if (!hasRecord) {
    return { ok: false, error: "no parcel data",
             detail: "the county portal returned no parcel record" };
  }
  return { ok: true, name: cfg.name, state: cfg.state, geoid: cfg.geoid,
           matches, sections };
}

// WTH GIS (Indiana): openMap -> map id, search.ashx -> feature id,
// getftr.aspx -> parcel overlay. Output is normalized into the same
// labeled-text section shape the analyzer's iasWorld parser reads.
async function wthLookup(cfg, number, street) {
  const headers = { "User-Agent": UA };
  const om = await fetch(
    `${cfg.base}/tgis/openMap.aspx?name=${encodeURIComponent(cfg.map)}`,
    { headers });
  const mid = (((await om.text()).match(/<mid>(\w+)<\/mid>/)) || [])[1];
  if (!mid) {
    return { ok: false, error: "portal changed", detail: "no map id" };
  }
  const q = encodeURIComponent(`${number} ${street}`);
  const sr = await fetch(
    `${cfg.base}/tgis/search.ashx?S=${q}&M=${mid}&U=1`, { headers });
  const rows = (await sr.text()).split("\n")
    .map(r => r.split("\x1f"))
    .filter(p => p.length >= 3 && p[1].trim() === "124");
  if (!rows.length) {
    return { ok: false, error: "no match",
             detail: "the address search returned no parcels — try just the " +
               "street number and street name (no suffix)" };
  }
  const ftrid = rows[0][2].trim();
  const g = await fetch(
    `${cfg.base}/tgis/getftr.aspx?D=124&F=${ftrid}&Z=1&redir=1&M=${mid}`,
    { headers });
  const text = stripHtml(await g.text());
  const grab = rx => { const m = text.match(rx); return m ? m[1].trim() : null; };
  const parid = grab(/StateParcelNumber\t([^\n]+)/) ||
                grab(/LocalParcelNumber\t([^\n]+)/);
  if (!parid) {
    return { ok: false, error: "no parcel data",
             detail: "the county portal returned no parcel record" };
  }
  const owner = grab(/OwnerName\t([^\n]+)/);
  const situs = grab(/LocationAddress\t([^\n]+)/);
  const acres = grab(/Acreage\t([\d.]+)/);
  const lines = [
    `Parcel Number: ${parid}`,
    owner ? `Parcel Owner: ${owner}` : "",
    situs ? `Parcel Address: ${situs}` : "",
    acres && +acres > 0 ? `Total Acres\t${acres}` : "",
  ];
  // Assessment table: "Type <tab> 2025 <tab> 2024 ..." + a "Totals" row.
  const ah = text.match(/Assessment Information\nType\t([^\n]+)/);
  const at = text.match(/Assessment Information[\s\S]{0,1500}?\nTotals\t([^\n]+)/);
  if (ah && at) {
    const years = ah[1].split("\t").map(s => s.trim());
    const totals = at[1].split("\t").map(s => s.trim().replace(/,/g, ""));
    years.forEach((y, i) => {
      if (/^\d{4}$/.test(y) && /^\d+$/.test(totals[i] || "") && +totals[i] > 0) {
        lines.push(`${y}\t${parid}\t$0\t$0\t$` +
          Number(totals[i]).toLocaleString("en-US"));
      }
    });
  }
  // Latest nonzero tax bill: "2024 Pay 2025 <tab> spring <tab> fall".
  for (const m of text.matchAll(/(\d{4}) Pay \d{4}\t([\d,.]+)\t([\d,.]+)/g)) {
    const spring = parseFloat(m[2].replace(/,/g, ""));
    const fall = parseFloat(m[3].replace(/,/g, ""));
    if (spring + fall > 0) {
      lines.push(`Real Estate\t0.00\t${m[2]}\t${m[3]}\t` +
        (spring + fall).toFixed(2));
      break; // rows are newest-first
    }
  }
  return { ok: true, name: cfg.name, state: cfg.state, geoid: cfg.geoid,
           matches: rows.length,
           sections: { profile: lines.filter(Boolean).join("\n") } };
}

export default {
  async fetch(request, env, ctx) {
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS });
    }
    if (request.method !== "GET") {
      return json({ ok: false, error: "GET only" }, 405);
    }
    const url = new URL(request.url);
    const slug = url.pathname.replace(/^\/+|\/+$/g, "");
    if (slug === "counties") {
      const list = Object.entries(COUNTIES).map(([k, c]) =>
        ({ route: k, geoid: c.geoid, name: c.name, state: c.state }));
      return json({ ok: true, counties: list },
                  200, { "Cache-Control": "public, max-age=3600" });
    }
    const cfg = COUNTIES[slug];
    if (!cfg) {
      return json({ ok: false, error: "unknown county route",
                    routes: Object.keys(COUNTIES).concat(["counties"]) }, 404);
    }
    const number = (url.searchParams.get("number") || "").trim();
    const street = (url.searchParams.get("street") || "").trim();
    if (!/^\d{1,6}$/.test(number) || street.length < 2 || street.length > 40) {
      return json({ ok: false, error: "bad query",
                    detail: "need number=<digits> and street=<name>" }, 400);
    }

    const cacheKey = new Request(url.toString(), { method: "GET" });
    const cache = caches.default;
    const hit = await cache.match(cacheKey);
    if (hit) return hit;

    let body;
    try {
      body = cfg.platform === "wth"
        ? await wthLookup(cfg, number, street)
        : await iasWorldLookup(cfg, number, street);
    } catch (err) {
      return json({ ok: false, error: "county fetch failed",
                    detail: String((err && err.message) || err) }, 502);
    }
    if (body.ok !== false) body.county = slug;
    const res = json(body, body.ok ? 200 : 404, {
      "Cache-Control": body.ok ? "public, max-age=86400" : "no-store",
    });
    if (body.ok) ctx.waitUntil(cache.put(cacheKey, res.clone()));
    return res;
  },
};
